### ISSUE TITLE
Small Issues to Address

### ISSUE THREAD

**Issue by TurtleP** [ellraiser/love-test#2]
## Description

There's a few issues I've run into while using this to test [LÖVE Potion](https://github.com/turtlep/lovepotion-experiments). Things I noticed through going into the test codebase trying to debug things on my end.

1. `love.draw` will call methods from `love.graphics` unconditionally. This can cause issues if `love.graphics` is disabled (or missing for some reason). This is also true during `TestSuite.lua` getting the renderer info.
2. `TestSuite.lua` should include the line number where the test failed. 
    - Tests seem to bail out the test as soon as an error happens, but having only a description doesn't always help: 
        - `[LOVE]  love.data.ByteData() ==> FAIL - 0.002s (0/0) - test failed - (attempt to index a string value)`
    - This doesn't tell me what line it failed on which hinders understanding where it failed.

---

I can help add some pull requests to fix these issues (might take a bit for the second item), but I figured these things should at least be noted.

**Comment by ellraiser** [comment]
Yo! Yeah those are both fair enough. I know the tests are ignored if the module doesn't exist but haven't tested module disabling for a while so must of missed those other uses. For the specific failures, line no. would be good for sure - usually the description is mostly unique per test assert but I can think of a few tests where every assert has mostly the same description without any numbering

I need to pull some latest changes from source soon so can look at doing those alongside that!

**Comment by TurtleP** [comment]
Yeah, it's quite frustrating. Currently on that repository I've got `xpcall` running `debug.traceback` on error. It's too verbose, but helps a bit.

```lua
self.test.co = coroutine.create(function()
  local ok, chunk, err = xpcall(function()
    love.test[love.test.module.module][method](love.test.test)
  end, debug.traceback)
  
  if ok == false then
    love.test.test['passed'] = false
    love.test.test['fatal'] = tostring(chunk) .. tostring(err)
  end
end)
```

One of the current failures I'm trying to fix is:

```
[LOVE]   love.data.decode()                        ==> FAIL - 0.003s (0/2) - code failed - ([string "tests/data.lua"]:124: Invalid size parameter (must be greater than 0).
stack traceback:
        [C]: in function 'getString'
        [string "tests/data.lua"]:124: in function '?'
        [string "classes/TestSuite.lua"]:80: in function <[string "classes/TestSuite.lua"]:79>
        [C]: in function 'xpcall'
        [string "classes/TestSuite.lua"]:79: in function <[string "classes/TestSuite.lua"]:78>nil)
```
This tells me *more* but I can't even tell which part of the assert is failing. Not sure if it can, though.

**Comment by ellraiser** [comment]
For that specific case, seems to imply that either `love.data.newByteData():getString()` or `love.data.decode():getString()` itself is failing when trying to get those values to assert? Give the initial failure you posted here I imagine it's `love.data.newByteData():getString()` specifically.

If the assert had failed it would be like "assert 'check data string' failed" in the output, using the description thats given as the final param of the assert methods

Although I can add some more helpful messaging to tell you what line a specific assert failed for a given test in this case it seems like the actual code inside the function is falling over instead of the results. I'm not sure how much I can do for that when the test suite is built for vanilla love and has some expectations with the methods used because of that

**Comment by TurtleP** [comment]
Yeah I'm trying to keep LÖVE Potion itself compatible with LÖVE, so there shouldn't need to be anything super specific added for my stuff (unlike with the Android port, for example).

**Comment by ellraiser** [comment]
Trying to recreate the error you're seeing here, if I add some borked code to a test method I just get an error like:

```love.data.ByteData()                      ==> FAIL - 0.021s (3/3) - code failed - (tests/data.lua:18: attempt to index local 'data' (a userdata value)nil)``` with the line number included

If it finds an error before an assert then it shows as "test failed" instead of "code failed", because no asserts were reached, so really I should fix that to make sure it's clearer on failure messages, but the error there is also:

```love.data.ByteData()                      ==> FAIL - 0.015s (0/0) - test failed - (tests/data.lua:16: attempt to index global 'f' (a nil value)nil)``` with the line number

This is on the latest test suite from source, but I haven't touched the logging in a few updates - so maybe specific to the platform you're logging on that for some reason it's not giving that extra line number info?

**Comment by TurtleP** [comment]
Hm.. we don't have LuaJIT on the consoles, so if that's part of it I don't know. Though the issue in question lies in my own C++ code, not Lua, which could also be the other reason.

**Comment by ellraiser** [comment]
Hmm okay, might have to skip that for now then until you have some more info or if its just specific to your situation

For the first `love.graphics` issue - looking into it seems like love ignores the `love.draw` hook entirely if you disable the graphics module in the `conf.lua` (or mess with `love.graphics` variable), so I probably won't be able to get a `if love.graphics` wrap added as it'll be seen as unnessecary

However I'll fix the use in TestSuite as its assuming its always loaded there

**Comment by TurtleP** [comment]
I think when I was doing the tests initially I didn't realize it was just the getRendererInfo call forcing it to exit - I just remember it was complaining `love.graphics` was nil when getting the error.

**Comment by TurtleP** [comment]
With the latest commits I also noticed that `TestSuite.lua` gets the current OS unconditionally from `love.system`. If memory serves, you can just use `love._os` as that is the same value (returns "Unknown" if system is not loaded).

**Comment by ellraiser** [comment]
Ah okay cool - will close this one for now with the latest changes but if you do work out whats going on with your c++ code and if there's something that can be done lemme know

Also good to know on `love._os` think I've seen that around before I'll try that!
